# Generated by Django 5.1.1 on 2024-09-21 09:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TheSafe_dbBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(max_length=255, unique_for_date='success')),
                ('success', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('noted', 'Noted'), ('reject', 'Reject'), ('success', 'Success')], default='success', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_posts', to=settings.AUTH_USER_MODEL)),
                ('theSafe_dbBox', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='safe.thesafe_dbbox')),
            ],
            options={
                'ordering': ('-success',),
            },
        ),
    ]
