# Generated by Django 5.1.1 on 2024-09-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0002_rename_post_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='balance',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='client',
            new_name='client_id',
        ),
    ]
