# Generated by Django 5.1.1 on 2024-09-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0003_rename_balance_progress_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TheSafe_dbBox',
            new_name='categorys',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='theSafe_dbBox',
            new_name='Categorys',
        ),
    ]
