# Generated by Django 5.1.1 on 2024-09-21 11:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0004_rename_thesafe_dbbox_categorys_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(max_length=255, unique_for_date='success')),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('noted', 'Noted'), ('reject', 'Reject'), ('success', 'Success')], default='success', max_length=100)),
                ('Categorys', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='safe.categorys')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-transaction_date',),
            },
        ),
        migrations.DeleteModel(
            name='progress',
        ),
    ]
