# Generated by Django 5.1.1 on 2024-09-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0005_transaction_delete_progress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categorys',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Categorys',
            new_name='Category',
        ),
    ]
