# Generated by Django 5.1.1 on 2024-09-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0007_alter_transaction_client_id_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-success',)},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='success',
        ),
    ]
