# Generated by Django 5.1.1 on 2024-09-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0008_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-transaction_date',)},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='success',
            new_name='transaction_date',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(max_length=255, unique_for_date='transaction_date'),
        ),
    ]
