# Generated by Django 5.1.1 on 2024-09-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0009_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='client_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
